"""SQLAlchemy ORM models for the interview trainer database."""
from datetime import datetime

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    # Allow legacy Column()-style annotations alongside Mapped[] in SQLAlchemy 2.x
    __allow_unmapped__ = True


class User(Base):
    """Registered Telegram users."""

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, autoincrement=True)
    telegram_id = Column(Integer, unique=True, nullable=False, index=True)
    username = Column(String(255), nullable=True)
    first_name = Column(String(255), nullable=True)
    preferred_role = Column(String(50), nullable=True)
    preferred_language = Column(String(10), nullable=True, default="en")
    preferred_voice = Column(String(20), nullable=True, default="alloy")
    preferred_ui_language = Column(String(10), nullable=True, default="en")
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    sessions = relationship("Session", back_populates="user", lazy="select")
    study_plans = relationship("StudyPlan", back_populates="user", lazy="select")


class Session(Base):
    """A single interview session."""

    __tablename__ = "sessions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    role = Column(String(50), nullable=False)
    experience_level = Column(String(50), nullable=False)
    mode = Column(String(20), nullable=False, server_default="technical")  # "technical" or "behavioral"
    company_id = Column(String(50), nullable=True)  # company set key (general, google, amazon, etc.)
    started_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    completed_at = Column(DateTime, nullable=True)
    total_score = Column(Float, nullable=True)
    completed = Column(Boolean, default=False, nullable=False)

    user = relationship("User", back_populates="sessions")
    answers = relationship(
        "Answer",
        back_populates="session",
        order_by="Answer.question_number",
    )


class Feedback(Base):
    """User feedback messages stored in the shared SQLite."""

    __tablename__ = "feedback"

    id = Column(Integer, primary_key=True, autoincrement=True)
    telegram_id = Column(Integer, nullable=False)
    username = Column(String(255), nullable=True)
    message = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class Answer(Base):
    """A single question-answer pair within a session."""

    __tablename__ = "answers"

    id = Column(Integer, primary_key=True, autoincrement=True)
    session_id = Column(Integer, ForeignKey("sessions.id"), nullable=False)
    question_number = Column(Integer, nullable=False)
    question_text = Column(Text, nullable=False)
    user_answer = Column(Text, nullable=False)
    score = Column(Integer, nullable=False)
    feedback = Column(Text, nullable=False)
    strengths = Column(Text, nullable=True)    # JSON-encoded list
    improvements = Column(Text, nullable=True)  # JSON-encoded list
    tip = Column(Text, nullable=True)
    category = Column(String(100), nullable=True)
    answered_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    session = relationship("Session", back_populates="answers")


class StudyPlan(Base):
    """A personalised study plan generated by AI based on interview performance."""

    __tablename__ = "study_plans"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    focus_areas = Column(Text, nullable=True)  # JSON-encoded list of strings
    duration_days = Column(Integer, nullable=False, default=7)
    status = Column(String(20), nullable=False, default="active")  # active | paused | completed
    progress_percent = Column(Integer, nullable=False, default=0)  # 0-100, computed
    source_type = Column(String(20), nullable=False, default="manual")  # manual | interview
    source_params = Column(Text, nullable=True)  # JSON: {mode, date_from, date_to, session_ids}
    language = Column(String(10), nullable=False, default="en")
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)

    user = relationship("User", back_populates="study_plans", foreign_keys=[user_id])
    days = relationship(
        "StudyPlanDay",
        back_populates="plan",
        order_by="StudyPlanDay.day_number",
        cascade="all, delete-orphan",
    )
    sessions = relationship(
        "StudyPlanSession",
        back_populates="plan",
        cascade="all, delete-orphan",
    )


class StudyPlanDay(Base):
    """A single day within a study plan."""

    __tablename__ = "study_plan_days"

    id = Column(Integer, primary_key=True, autoincrement=True)
    plan_id = Column(Integer, ForeignKey("study_plans.id"), nullable=False, index=True)
    day_number = Column(Integer, nullable=False)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    resources = Column(Text, nullable=True)  # JSON-encoded list of {title, url, type}
    estimated_minutes = Column(Integer, nullable=True)
    is_completed = Column(Boolean, default=False, nullable=False)
    completed_at = Column(DateTime, nullable=True)

    plan = relationship("StudyPlan", back_populates="days")


class StudyPlanSession(Base):
    """Links a study plan to the interview sessions it was generated from."""

    __tablename__ = "study_plan_sessions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    plan_id = Column(Integer, ForeignKey("study_plans.id"), nullable=False, index=True)
    session_id = Column(Integer, ForeignKey("sessions.id"), nullable=False)

    plan = relationship("StudyPlan", back_populates="sessions")


class SystemDesignSession(Base):
    """A guided 7-step system design interview session (Premium feature)."""

    __tablename__ = "sd_sessions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    problem = Column(String(100), nullable=False)  # "Design YouTube", "Design Twitter", etc.
    level = Column(String(50), nullable=True)
    company = Column(String(50), nullable=True, default="general")
    current_step = Column(Integer, default=1)  # 1-7
    step_scores = Column(Text, default="[]")   # JSON: [{"step": 1, "score": 8}, ...]
    step_context = Column(Text, default="[]")  # JSON: [{step, step_name, prompt, answer, score, feedback}]
    summary = Column(Text, nullable=True)      # JSON: final evaluation dict
    started_at = Column(DateTime, default=datetime.utcnow)
    completed = Column(Boolean, default=False)
    total_score = Column(Float, nullable=True)
